export const ALL_RECIPE_REQUEST = "ALL_RECIPE_REQUEST";
export const ALL_RECIPE_SUCCESS = "ALL_RECIPE_SUCCESS";
export const ALL_RECIPE_FAIL = "ALL_RECIPE_FAIL";

export const RECIPE_DETAILS_REQUEST = "RECIPE_DETAILS_REQUEST";
export const RECIPE_DETAILS_SUCCESS = "RECIPE_DETAILS_SUCCESS";
export const RECIPE_DETAILS_FAIL = "RECIPE_DETAILS_FAIL";

export const MY_RECIPES_REQUEST = "MY_RECIPES_REQUEST";
export const MY_RECIPES_SUCCESS = "MY_RECIPES_SUCCESS";
export const MY_RECIPES_FAIL = "MY_RECIPES_FAIL";

export const USER_RECIPES_REQUEST = "USER_RECIPES_REQUEST";
export const USER_RECIPES_SUCCESS = "USER_RECIPES_SUCCESS";
export const USER_RECIPES_FAIL = "USER_RECIPES_FAIL";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_RESET = "ADD_COMMENT_RESET";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const NEW_RECIPE_REQUEST = "NEW_RECIPE_REQUEST";
export const NEW_RECIPE_SUCCESS = "NEW_RECIPE_SUCCESS";
export const NEW_RECIPE_RESET = "NEW_RECIPE_RESET";
export const NEW_RECIPE_FAIL = "NEW_RECIPE_FAIL";

export const DELETE_RECIPE_REQUEST = "DELETE_RECIPE_REQUEST";
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_RESET = "DELETE_RECIPE_RESET";
export const DELETE_RECIPE_FAIL = "DELETE_RECIPE_FAIL";

export const UPDATE_RECIPE_REQUEST = "UPDATE_RECIPE_REQUEST";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const UPDATE_RECIPE_RESET = "UPDATE_RECIPE_RESET";
export const UPDATE_RECIPE_FAIL = "UPDATE_RECIPE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";